// Visual mnemonics for katakana, adapted with permission from the « Akemi no Sekai » blog:
// https://akeminosekai.gitlab.io/japonais_1.html
export const KATAKANA_TIPS = {
  "ア": "On dirait un « p » : comme dans « PAPA », plein de A.",
  "イ": "Un « i » dont le point a glissé sur le côté.",
  "ウ": "Comme う avec un chapeau ; tourne-le et tu vois un « u ».",
  "エ": "Un tracé tout droit et régulier, comme une HAIE (« é ») bien taillée.",
  "オ": "Un bonhomme en fil de fer pas fini : un « demi-homme », OH ! (le complet, c'est ホ)",
  "カ": "Un homme avec un gros CArtable sur le dos.",
  "キ": "Une clé (« KEY ») à trois traits.",
  "ク": "La faux de la mort, qui sert à COUper.",
  "ケ": "Comme ク, mais le trait horizontal est plus long et dépasse à droite.",
  "コ": "Un KOala agrippé à une branche.",
  "サ": "Le visage d'un SAge.",
  "シ": "SHI : un visage triste, les deux yeux À PLAT et la bouche qui remonte du bas. (≠ ツ)",
  "ス": "Un petit abri pour se mettre « SOUS » (SU).",
  "セ": "Le profil d'un vieil Espagnol avec son chapeau, qui dit « SEñor ».",
  "ソ": "SO : un visage radieux avec UN SEUL œil presque vertical, le grand trait tombe du haut. (≠ ン)",
  "タ": "Penche-le : on voit une TAble ou un TAbouret.",
  "チ": "Une branche (1er trait) où pend CHIta, le singe de Tarzan.",
  "ツ": "TSU : un visage tout content, les yeux DEBOUT, qui crie « TSUki ! » (la lune). (≠ シ)",
  "テ": "On y voit un « t » : TÉ.",
  "ト": "Ressemble à un « t » : TO.",
  "ナ": "Une croix penchée : une femme qui a lâché sa poupée — NA !",
  "ニ": "Deux traits = 2, qui se dit NI en japonais !",
  "ヌ": "On dirait un 7… et « NOUille » s'écrit en 7 lettres.",
  "ネ": "Un NEZ qui coule (avec la morve qui goutte).",
  "ノ": "Un trait tout seul, comme « NO one » : personne.",
  "ハ": "Un chemin vers le paradis où chante un chœur d'anges : « HA-lleluia ! »",
  "ヒ": "La bouche d'un bonhomme qui plane avec sa pipe : HI hi.",
  "フ": "Le mont FUji tout penché.",
  "ヘ": "Le vent sur les montagnes — identique au hiragana へ !",
  "ホ": "Un samouraï complet avec ses deux katana : HO ! (le demi-homme, c'est オ)",
  "マ": "On dirait un « 1 » : MA est la 1re syllabe de la ligne des M.",
  "ミ": "Tourne-le : un « m » à trois traits. (ニ en a deux)",
  "ム": "Un bras plié avec un gros MUscle.",
  "メ": "Une croix, comme sur la tombe de MÉmé.",
  "モ": "Un « t » avec deux barres au lieu d'une : en japonais, « encore plus » se dit MOtto !",
  "ヤ": "On y voit un « y » et un « a » : YA.",
  "ユ": "Un « y » à l'envers et un « u » : YU.",
  "ヨ": "Un gros E en miroir, ou une main levée qui dit « YO ! »",
  "ラ": "Relie les traits : un 5, comme « 5 RATS qui te chient dessus ».",
  "リ": "Un grain de RIz, comme le hiragana り.",
  "ル": "La voie du milieu d'une RUe.",
  "レ": "Le trait qui repart vers la droite : un REtour.",
  "ロ": "Une bouche grande ouverte qui ROte.",
  "ワ": "Retourne-le en miroir et couche-le : un « w ». (ウ a un chapeau, フ n'a pas le petit trait devant)",
  "ヲ": "Couché sur le côté, on voit un « w » : WO (se lit « o »). Il a un trait de plus que ワ.",
  "ン": "N : un smiley qui fait la tête, UN SEUL œil, et la bouche part d'en bas à gauche. (≠ ソ, シ, ツ)"
};
